export const cinemaData = [
  {
    id: 1,
    salon: 1,
    filmAdi: "Recep Ivedik",
    fiyat: 15,
    tarih: new Date(),
    koltuklar: [
      { id: 1, alinabilir: 1, secildi: 0 },
      { id: 2, alinabilir: 1, secildi: 0 },
      { id: 3, alinabilir: 0, secildi: 0 },
      { id: 4, alinabilir: 1, secildi: 0 },
      { id: 5, alinabilir: 0, secildi: 0 },
      { id: 6, alinabilir: 0, secildi: 0 },
      { id: 7, alinabilir: 1, secildi: 0 },
      { id: 8, alinabilir: 0, secildi: 0 },
      { id: 9, alinabilir: 1, secildi: 0 },
      { id: 10, alinabilir: 1, secildi: 0 },
      { id: 11, alinabilir: 1, secildi: 0 },
      { id: 12, alinabilir: 1, secildi: 0 },
      { id: 13, alinabilir: 1, secildi: 0 },
      { id: 14, alinabilir: 1, secildi: 0 },
      { id: 15, alinabilir: 0, secildi: 0 },
      { id: 16, alinabilir: 0, secildi: 0 },
      { id: 17, alinabilir: 1, secildi: 0 },
      { id: 18, alinabilir: 0, secildi: 0 },
      { id: 19, alinabilir: 0, secildi: 0 },
      { id: 20, alinabilir: 1, secildi: 0 },
      { id: 21, alinabilir: 1, secildi: 0 },
      { id: 22, alinabilir: 0, secildi: 0 },
      { id: 23, alinabilir: 1, secildi: 0 },
      { id: 24, alinabilir: 1, secildi: 0 },
      { id: 25, alinabilir: 0, secildi: 0 },
      { id: 26, alinabilir: 0, secildi: 0 },
      { id: 27, alinabilir: 1, secildi: 0 },
      { id: 28, alinabilir: 1, secildi: 0 },
      { id: 29, alinabilir: 1, secildi: 0 },
      { id: 30, alinabilir: 1, secildi: 0 },
      { id: 31, alinabilir: 1, secildi: 0 },
      { id: 32, alinabilir: 1, secildi: 0 },
      { id: 33, alinabilir: 0, secildi: 0 },
      { id: 34, alinabilir: 0, secildi: 0 },
      { id: 35, alinabilir: 0, secildi: 0 },
      { id: 36, alinabilir: 0, secildi: 0 },
      { id: 37, alinabilir: 1, secildi: 0 },
      { id: 38, alinabilir: 1, secildi: 0 },
      { id: 39, alinabilir: 1, secildi: 0 },
      { id: 40, alinabilir: 1, secildi: 0 },
    ],
  },
  {
    id: 2,
    salon: 2,
    filmAdi: "Yuzuklerin Efendisi",
    fiyat: 25,
    tarih: new Date(),
    koltuklar: [
      { id: 1, alinabilir: 0, secildi: 0 },
      { id: 2, alinabilir: 0, secildi: 0 },
      { id: 3, alinabilir: 1, secildi: 0 },
      { id: 4, alinabilir: 1, secildi: 0 },
      { id: 5, alinabilir: 1, secildi: 0 },
      { id: 6, alinabilir: 0, secildi: 0 },
      { id: 7, alinabilir: 1, secildi: 0 },
      { id: 8, alinabilir: 1, secildi: 0 },
      { id: 9, alinabilir: 0, secildi: 0 },
    ],
  },
  {
    id: 3,
    salon: 3,
    filmAdi: "Forrest Gump",
    fiyat: 25,
    tarih: new Date(),
    koltuklar: [
      { id: 1, alinabilir: 0, secildi: 0 },
      { id: 2, alinabilir: 0, secildi: 0 },
      { id: 3, alinabilir: 1, secildi: 0 },
      { id: 4, alinabilir: 1, secildi: 0 },
      { id: 5, alinabilir: 1, secildi: 0 },
      { id: 6, alinabilir: 0, secildi: 0 },
      { id: 7, alinabilir: 1, secildi: 0 },
      { id: 8, alinabilir: 1, secildi: 0 },
      { id: 9, alinabilir: 0, secildi: 0 },
    ],
  },
  {
    id: 4,
    salon: 4,
    filmAdi: "Gorevimiz Tehlike",
    fiyat: 25,
    tarih: new Date(),
    koltuklar: [
      { id: 1, alinabilir: 0, secildi: 0 },
      { id: 2, alinabilir: 0, secildi: 0 },
      { id: 3, alinabilir: 1, secildi: 0 },
      { id: 4, alinabilir: 1, secildi: 0 },
      { id: 5, alinabilir: 1, secildi: 0 },
      { id: 6, alinabilir: 0, secildi: 0 },
      { id: 7, alinabilir: 1, secildi: 0 },
      { id: 8, alinabilir: 1, secildi: 0 },
      { id: 9, alinabilir: 0, secildi: 0 },
    ],
  },
  {
    id: 5,
    salon: 3,
    filmAdi: "BABA",
    fiyat: 25,
    tarih: new Date(),
    koltuklar: [
      { id: 1, alinabilir: 0, secildi: 0 },
      { id: 2, alinabilir: 0, secildi: 0 },
      { id: 3, alinabilir: 1, secildi: 0 },
      { id: 4, alinabilir: 1, secildi: 0 },
      { id: 5, alinabilir: 1, secildi: 0 },
      { id: 6, alinabilir: 0, secildi: 0 },
      { id: 7, alinabilir: 1, secildi: 0 },
      { id: 8, alinabilir: 1, secildi: 0 },
      { id: 9, alinabilir: 0, secildi: 0 },
    ],
  },
  {
    id: 6,
    salon: 4,
    filmAdi: "Batman",
    fiyat: 25,
    tarih: new Date(),
    koltuklar: [
      { id: 1, alinabilir: 0, secildi: 0 },
      { id: 2, alinabilir: 0, secildi: 0 },
      { id: 3, alinabilir: 1, secildi: 0 },
      { id: 4, alinabilir: 1, secildi: 0 },
      { id: 5, alinabilir: 1, secildi: 0 },
      { id: 6, alinabilir: 0, secildi: 0 },
      { id: 7, alinabilir: 1, secildi: 0 },
      { id: 8, alinabilir: 1, secildi: 0 },
      { id: 9, alinabilir: 0, secildi: 0 },
      { id: 10, alinabilir: 0, secildi: 0 },
      { id: 11, alinabilir: 0, secildi: 0 },
      { id: 12, alinabilir: 1, secildi: 0 },
      { id: 13, alinabilir: 0, secildi: 0 },
      { id: 14, alinabilir: 1, secildi: 0 },
      { id: 15, alinabilir: 0, secildi: 0 },
      { id: 16, alinabilir: 0, secildi: 0 },
      { id: 17, alinabilir: 1, secildi: 0 },
      { id: 18, alinabilir: 1, secildi: 0 },
      { id: 19, alinabilir: 0, secildi: 0 },
      { id: 20, alinabilir: 0, secildi: 0 },

    ],
  },
  {
    id: 7,
    salon: 1,
    filmAdi: "Avatar",
    fiyat: 25,
    tarih: new Date(),
    koltuklar: [
      { id: 1, alinabilir: 0, secildi: 0 },
      { id: 2, alinabilir: 0, secildi: 0 },
      { id: 3, alinabilir: 1, secildi: 0 },
      { id: 4, alinabilir: 1, secildi: 0 },
      { id: 5, alinabilir: 1, secildi: 0 },
      { id: 6, alinabilir: 0, secildi: 0 },
      { id: 7, alinabilir: 1, secildi: 0 },
      { id: 8, alinabilir: 1, secildi: 0 },
      { id: 9, alinabilir: 0, secildi: 0 },
    ],
  },
];
